added "experiment" type method to pdb_search
aion-labs/aiondata pull request #5
Opened 2024-07-08 15:57 UTC by tomshani

I added the necessary addition to the unit test...hope there's no issue

2024-07-09 17:49 UTC, jbenjoseph requested changes
Can you run this code though the black formatter?

`pip install pre-commit && pre-commit install && pre-commit run --all-files`

2024-07-21 07:45 UTC, jbenjoseph requested changes
Make sure self is the first parameter of all Object methods.

2024-07-21 07:45 UTC, jbenjoseph commented on aiondata/raw/protein_structure.py
>      def fetch_uniprot_sequence(uniprot_id):
Missing self parameter

2024-08-07 07:41 UTC, tomshani commented on aiondata/raw/protein_structure.py
>      def fetch_uniprot_sequence(uniprot_id):
fixed

2024-08-07 07:54 UTC, merged